builds:
  - binary: nepcal
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

brew:
  name: nepcal
  github:
    owner: nepcal
    name: nepcal
  folder: Formula
  homepage: https://github.com/nepcal/nepcal
  description: Equivalent of Linux's cal, for Nepali dates
  build_dependencies:
    - make

